### ISSUE TITLE
FR: Choose location

### ISSUE THREAD

**Issue by Lotus49b** [inhumantsar/slurp-extension#1]
Hi, thanks for this plugin - looking very useful.

FR: Make the Slurp directory selectable. It seems to simply create a "Slurp" directory at root level. I'd want to decide where to fit into my current directory structure, e.g. Inbox/New notes.

**Comment by inhumantsar** [comment]
I'm actually in the process of making this happen on the plugin's side. Currently setting it up as a single destination. ie: in settings you could change "Slurped Pages" to "Inbox" and from then on all new slurped Pages would be saved to Inbox.

Are you looking to be able to select a directory for each save? ie: press the slurp button and a dialog comes up giving you the choice between using the configured setting and overriding it?

**Comment by inhumantsar** [comment]
this is out now in v0.1.6 as well 😄 

see also https://github.com/inhumantsar/slurp/issues/9

**Comment by Lotus49b** [comment]
> I'm actually in the process of making this happen on the plugin's side. Currently setting it up as a single destination. ie: in settings you could change "Slurped Pages" to "Inbox" and from then on all new slurped Pages would be saved to Inbox.
> 
> Are you looking to be able to select a directory for each save? ie: press the slurp button and a dialog comes up giving you the choice between using the configured setting and overriding it?

No, just a general destination is good.
